name: Infra setup in AWS
on:
  workflow_dispatch:
  
env:
  AWS_REGION: us-east-1     # Update this to your AWS Region
  TF_ACTION_WORKING_DIR: 'terraform' # Update this to your Terraform files directory

jobs:
  setu-AWS-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: ${{ env.AWS_REGION }} # Use the region from your environment variables

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Initialize
      run: |
        cd setup/terraform && terraform init

    - name: Terraform Validate
      run: |
        cd setup/terraform && terraform validate 

    - name: Terraform Plan
      run: |
         cd setup/terraform && terraform plan 
      continue-on-error: true

    - name: Terraform Apply
     # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
         echo github.ref
         echo github.event_name
         cd setup/terraform && terraform apply -auto-approve
         continue-on-error: true

    - name: Terraform Destroy
      run:  terraform apply -destroy
        